Feature/no transfer unread
codeforamerica/clientcomm-rails pull request #121
Opened 2018-04-02 18:39 UTC by glassresistor

2018-04-02 22:10 UTC, glassresistor commented
@tmaybe please review and merge

2018-04-03 18:21 UTC, tmaybe requested changes
I added some comments for suggested changes to tests.

Also, verify with @alsomanya that this current behavior is correct: we don't mark messages read if it's a user doing the transfer.

2018-04-03 18:21 UTC, tmaybe commented on spec/features/admin_spec.rb
> +          expect(page).to have_content('This client has unread messages. The messages will not be transferred to the new user.')
use the I18n string `I18n.t('views.admin.reporting_relationships.edit.unread_transfer')`

2018-04-03 18:21 UTC, tmaybe commented on spec/features/admin_spec.rb
> +          msg = create :message, reporting_relationship: ReportingRelationship.find_by(user: user1, client: client1), read: false
Set `has_unread_messages` on the reporting relationship to true as well.

2018-04-03 18:21 UTC, tmaybe commented on spec/features/admin_spec.rb
> +          expect(msg.reload).to be_read
expect `has_unread_messages` on the reporting relationship to be false as well.

2018-04-03 18:21 UTC, tmaybe commented on spec/features/user_edits_client_spec.rb
> +      create :message, reporting_relationship: rr, read: false, inbound: true
set `has_unread_messages` on the reporting relationship to true as well

2018-04-03 18:21 UTC, tmaybe commented on spec/features/user_edits_client_spec.rb
> +  let(:unread_error_message) { 'This client has unread messages. The messages will not be transferred to the new user. Transfer now, or click here to read them.' }
use the I18n string `I18n.t('views.clients.edit.manage.unread_transfer')`

2018-04-03 18:21 UTC, tmaybe commented on spec/features/user_edits_client_spec.rb
> +      expect(page).to_not have_content('This client has unread messages. The messages will not be transferred to the new user. Transfer now, or click here to read them.')
Use the variable for this string (and/or the I18n value)

2018-04-03 18:21 UTC, tmaybe commented on spec/features/user_edits_client_spec.rb
> +
Add a test for what happens when there's a warning and the user transfers the client; it should check the `read` value of the message and the `has_unread_messages` value of the reporting relationship.

2018-04-03 18:43 UTC, glassresistor commented
@alsomanya says to mark them as read.  so the code should work as implemented.  working on i18n stuff now.  Wanted to but i think we might have to transform some.

I'll add the has_unread_message checks and make sure that happens, good catch,

2018-04-19 17:13 UTC, closed without merging