Edit client
codeforamerica/clientcomm-rails pull request #57
Opened 2017-06-26 15:32 UTC by cweems

Hold - not ready for merging.

2017-06-26 22:05 UTC, cweems commented
@tmaybe @alsomanya @disambiguator Think this is good to go! Review would be appreciated.

2017-06-26 22:49 UTC, alsomanya commented on app/views/clients/_clients.html.erb
> +    <td><%= link_to 'Edit', edit_client_path(client) %></td>
Instead of the word "Edit", can we use the settings icon GCF uses (`<i class="icon-settings"></i>`)?

2017-06-26 22:50 UTC, alsomanya commented on app/views/messages/index.html.erb
> +      </div>
Same q as above — can we use the icon here?

2017-06-26 23:00 UTC, alsomanya commented
design LGTM — @cweems and I agreed on keeping the edit action as the word "Edit" for now and only moving to iconography if/when we have multiple actions a case manager can take from the dashboard.

2017-06-27 07:44 UTC, tmaybe requested changes
see comments; also should track edit events.

2017-06-27 07:44 UTC, tmaybe commented on app/views/messages/index.html.erb
> +          <h2 style="float: left" class="client-name"><%= @client.full_name %>&nbsp</h2>
I prefer to not have in-line css, and to not use `&nbsp;`s for spacing.

2017-06-27 07:44 UTC, tmaybe commented on spec/features/user_creates_client_spec.rb
> +feature "User edits client" do
Move client edit tests into their own file, and test one thing at a time.

2017-06-27 07:44 UTC, tmaybe commented on app/views/clients/edit.html.erb
> +<div class="slab">
This form is identical to the new client form, it should be moved into a partial.

2017-06-27 07:59 UTC, tmaybe approved these changes

2017-06-27 08:02 UTC, merged