Combine feature spec into a journey-style BDD test
codeforamerica/clientcomm-rails pull request #66
Opened 2017-06-30 20:54 UTC by disambiguator

* Inline gcf_send_message_field

2017-06-30 21:34 UTC, tmaybe requested changes
The spec change looks good to me, but the change to the send message field introduces some bugs. They should either be fixed or removed from this PR.

2017-06-30 21:34 UTC, tmaybe commented on app/views/messages/index.html.erb
> +      <%= form_for @message, remote: true, :html => {class: 'sendbar form-width--searchbar' }, builder: GcfFormBuilder do |f| %>
do we still need `builder: GcfFormBuilder` here?

2017-06-30 21:34 UTC, tmaybe commented on app/views/messages/index.html.erb
> +      <%= form_for @message, remote: true, :html => {class: 'sendbar form-width--searchbar' }, builder: GcfFormBuilder do |f| %>
This breaks the field layout; on mobile, the field stretches off screen:
![screen shot 2017-06-30 at 2 30 03 pm](https://user-images.githubusercontent.com/546665/27754746-c8f84db4-5da0-11e7-9b3b-253363b3a1b1.png)

On desktop, the button is misaligned with the field:
![screen shot 2017-06-30 at 2 30 20 pm](https://user-images.githubusercontent.com/546665/27754749-cef7a642-5da0-11e7-8998-07839a40646e.png)

this is how it should look:
![screen shot 2017-06-30 at 2 32 18 pm](https://user-images.githubusercontent.com/546665/27754767-f40df3c8-5da0-11e7-8c21-0f57c7166543.png)

2017-06-30 21:34 UTC, tmaybe commented on app/views/messages/index.html.erb
> +      <%= form_for @message, remote: true, :html => {class: 'sendbar form-width--searchbar' }, builder: GcfFormBuilder do |f| %>
Feel free to remove this part of the commit from the PR, since it's not really related to the feature spec changes.

2017-07-05 16:58 UTC, cweems commented on app/views/messages/index.html.erb
> +      <%= form_for @message, remote: true, :html => {class: 'sendbar form-width--searchbar' }, builder: GcfFormBuilder do |f| %>
@disambiguator @tmaybe I'll do this quick right now.

2017-07-05 18:20 UTC, cweems commented on app/views/messages/index.html.erb
> +      <%= form_for @message, remote: true, :html => {class: 'sendbar form-width--searchbar' }, builder: GcfFormBuilder do |f| %>
It would appear that we don't. Removed it.

2017-07-05 18:20 UTC, disambiguator commented on app/views/messages/index.html.erb
> +          <button id="send_message" class="sendbar__button button--primary" type="submit">Send</button>
Button still cuts off when you shrink the window. :(

2017-07-05 18:23 UTC, cweems commented on app/views/messages/index.html.erb
> +          <button id="send_message" class="sendbar__button button--primary" type="submit">Send</button>
You're totally right - give me a sec and I'll fix it.

2017-07-05 18:24 UTC, cweems commented on app/views/messages/index.html.erb
> +          <button id="send_message" class="sendbar__button button--primary" type="submit">Send</button>
#justusebootstrap

2017-07-05 18:24 UTC, tmaybe commented on app/views/messages/index.html.erb
> +          <button id="send_message" class="sendbar__button button--primary" type="submit">Send</button>
We're going to be changing the design of the send message form anyway (adding the `Send later` button) so lets not get too wrapped up in making the original design look right.

2017-07-05 18:27 UTC, cweems commented on app/views/messages/index.html.erb
> +          <button id="send_message" class="sendbar__button button--primary" type="submit">Send</button>
<img width="322" alt="screen shot 2017-07-05 at 11 26 50 am" src="https://user-images.githubusercontent.com/1418949/27878967-eaa4809a-6174-11e7-9c83-1bf39a996a9b.png">
<img width="1440" alt="screen shot 2017-07-05 at 11 27 00 am" src="https://user-images.githubusercontent.com/1418949/27878966-eaa1f6cc-6174-11e7-8797-8d8b5aff0b7e.png">

Ok, think this works now.

2017-07-05 18:29 UTC, tmaybe commented on app/views/messages/index.html.erb
> +          <button id="send_message" class="sendbar__button button--primary" type="submit">Send</button>
Checking it now...

2017-07-05 18:30 UTC, cweems commented on app/views/messages/index.html.erb
> +          <button id="send_message" class="sendbar__button button--primary" type="submit">Send</button>
@tmaybe sorry you might need to pull, just pushed it

2017-07-05 18:42 UTC, tmaybe approved these changes

2017-07-05 18:49 UTC, merged