Scheduled messages
codeforamerica/clientcomm-rails pull request #69
Opened 2017-07-05 21:11 UTC by cweems

Not ready for merge.

2017-07-07 01:52 UTC, disambiguator commented
fyi the Send Later button stacks downwards as you shrink the button.

2017-07-12 18:06 UTC, zaksoup commented
We need to write a test for the new scheduled message job

2017-07-14 01:39 UTC, disambiguator commented on .env.example
> +DEPLOY_BASE_URL= #required for analytics helper tests (for now)
Can someone run me through what this means eventually?

2017-07-14 09:59 UTC, tmaybe requested changes

2017-07-14 09:59 UTC, tmaybe commented on app/controllers/messages_controller.rb
> +      label = 'message_sent_immediately'
should be `message_send`

2017-07-14 09:59 UTC, tmaybe commented on app/controllers/messages_controller.rb
> +      label = 'message_scheduled'
should be `message_schedule`

2017-07-14 09:59 UTC, tmaybe commented on db/migrate/20170706230335_add_send_date_to_messages.rb
> +    add_column :messages, :send_date, :datetime
Can we name it `:send_at` instead of `:send_date`, to conform with the other datetime columns in the table? (`:created_at`, `:updated_at`)

2017-07-14 09:59 UTC, tmaybe commented on spec/features/user_sends_message_to_client_spec.rb
> +  skip 'user schedules a message to client', :js do
why skipped?

2017-07-14 16:11 UTC, zaksoup commented on spec/features/user_sends_message_to_client_spec.rb
> +  skip 'user schedules a message to client', :js do
It'll fail on master until we've finished implementing the rest of the UI changes as this test is based on the final UI designs.

2017-07-14 21:28 UTC, tmaybe approved these changes

2017-07-14 21:33 UTC, merged