Message styling
codeforamerica/clientcomm-rails pull request #76
Opened 2017-07-10 20:41 UTC by cweems

Changes the layout of the message bubbles so that they are the width of the text that they contain (rather than being fixed width). On mobile, message bubbles will be 100% the width of the container.

Also removes the use of flexbox CSS, making the messages view compatible with older browsers.

![screen shot 2017-07-10 at 1 39 18 pm](https://user-images.githubusercontent.com/1418949/28038884-40936dd2-6575-11e7-8a57-71fc91071047.png)
![screen shot 2017-07-10 at 1 39 34 pm](https://user-images.githubusercontent.com/1418949/28038885-40964a8e-6575-11e7-8b36-823731b9954c.png)

2017-07-10 20:56 UTC, tmaybe requested changes
Looks great to me! I made one small change request, but aside from that, if Manya's good with the visual/UX, I think it's good to go.

2017-07-10 20:56 UTC, tmaybe commented on app/assets/stylesheets/templates/_messages.scss
> +          right: 1.5em;
Could you assign a variable for this value (`1.5em` or an equivalent in `rem`) in `app/assets/stylesheets/atoms/_variables.scss` and use it above, and on lines 74-75?

2017-07-10 23:34 UTC, alsomanya commented on app/assets/stylesheets/templates/_messages.scss
> +          right: 1.5em;
In the screenshots the padding looks a little bigger than what's currently on production. is 1.5em the same amount?

2017-07-12 00:51 UTC, cweems commented
@tmaybe This should be good to go!

2017-07-12 03:30 UTC, tmaybe approved these changes
Looks great! merging.

2017-07-12 03:30 UTC, merged